import { RoadmapData } from '../types'

export const contentMarketingRoadmap: RoadmapData = {
  slug: 'content-marketing',
  title: 'Content Marketing',
  description: 'Build authority through strategic content, distribution systems, and audience development.',
  icon: '✍️',
  difficulty: 'beginner',
  duration: '3-5 months',
  totalTopics: 11,
  
  nodes: [
    {
      id: 'start',
      title: 'START',
      x: 300,
      y: 20,
      width: 200,
      height: 60,
      status: 'completed',
      description: 'Begin your content marketing journey',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'fundamentals',
      title: 'Content Strategy Basics',
      subtitle: 'Purpose · Audience · Goals',
      x: 250,
      y: 120,
      width: 300,
      height: 80,
      status: 'completed',
      description: 'Learn the fundamentals of content strategy including defining purpose, identifying audience, and setting measurable goals.',
      whatYouLearn: [
        'Content strategy framework',
        'Audience research and persona development',
        'Setting content goals and KPIs',
        'Content audit methodology',
      ],
      frameworks: [
        { name: 'Content Strategy Framework', link: '/frameworks/content-strategy' },
        { name: 'Audience Persona Template', link: '/frameworks/audience-personas' },
        { name: 'Content Goals Canvas', link: '/frameworks/content-goals' },
      ],
      prerequisites: [],
    },
    {
      id: 'ideation',
      title: 'Content Ideation',
      subtitle: 'Research · Topics · Angles',
      x: 250,
      y: 240,
      width: 300,
      height: 80,
      status: 'in-progress',
      description: 'Master systematic content ideation through keyword research, topic clustering, and finding unique angles.',
      whatYouLearn: [
        'Keyword research techniques',
        'Topic clustering methodology',
        'Finding unique content angles',
        'Content gap analysis',
      ],
      frameworks: [
        { name: 'Content Ideation System', link: '/frameworks/content-ideation' },
        { name: 'Topic Cluster Model', link: '/frameworks/topic-clusters' },
        { name: 'Keyword Research Framework', link: '/frameworks/keyword-research' },
      ],
      prerequisites: ['Content Strategy Basics'],
    },
    {
      id: 'creation',
      title: 'Content Creation',
      subtitle: 'Writing · Production · Quality',
      x: 100,
      y: 360,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Develop content creation skills including writing, production workflows, and maintaining quality standards.',
      whatYouLearn: [
        'Writing for different formats',
        'Content production workflows',
        'Quality control processes',
        'Editing and optimization',
      ],
      frameworks: [
        { name: 'Content Production System', link: '/frameworks/content-production' },
        { name: 'Writing Framework', link: '/frameworks/writing-framework' },
        { name: 'Content Quality Checklist', link: '/frameworks/content-quality' },
      ],
      prerequisites: ['Content Ideation'],
    },
    {
      id: 'seo',
      title: 'SEO for Content',
      subtitle: 'On-page · Technical · Links',
      x: 400,
      y: 360,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Optimize content for search engines through on-page SEO, technical optimization, and link building.',
      whatYouLearn: [
        'On-page SEO best practices',
        'Technical SEO fundamentals',
        'Internal linking strategy',
        'Building quality backlinks',
      ],
      frameworks: [
        { name: 'SEO Content Checklist', link: '/frameworks/seo-content' },
        { name: 'Technical SEO Guide', link: '/frameworks/technical-seo' },
        { name: 'Link Building Strategy', link: '/frameworks/link-building' },
      ],
      prerequisites: ['Content Ideation'],
    },
    {
      id: 'distribution',
      title: 'Content Distribution',
      subtitle: 'Channels · Promotion · Amplification',
      x: 250,
      y: 480,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Build systematic distribution strategies across owned, earned, and paid channels.',
      whatYouLearn: [
        'Multi-channel distribution strategy',
        'Content promotion tactics',
        'Social media amplification',
        'Community distribution',
      ],
      frameworks: [
        { name: 'Distribution Matrix', link: '/frameworks/distribution-matrix' },
        { name: 'Content Promotion Playbook', link: '/frameworks/content-promotion' },
        { name: 'Amplification Strategy', link: '/frameworks/amplification' },
      ],
      prerequisites: ['Content Creation', 'SEO for Content'],
    },
    {
      id: 'repurposing',
      title: 'Content Repurposing',
      subtitle: 'Formats · Atomization · Leverage',
      x: 250,
      y: 600,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Maximize content ROI through strategic repurposing across formats and channels.',
      whatYouLearn: [
        'Content atomization strategy',
        'Format adaptation techniques',
        'Repurposing workflows',
        'Maximizing content leverage',
      ],
      frameworks: [
        { name: 'Content Repurposing System', link: '/frameworks/content-repurposing' },
        { name: 'Format Adaptation Guide', link: '/frameworks/format-adaptation' },
        { name: 'Content Leverage Matrix', link: '/frameworks/content-leverage' },
      ],
      prerequisites: ['Content Distribution'],
    },
    {
      id: 'measurement',
      title: 'Content Analytics',
      subtitle: 'Metrics · Tracking · Insights',
      x: 250,
      y: 720,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Measure content performance and derive insights to improve strategy.',
      whatYouLearn: [
        'Content metrics and KPIs',
        'Analytics setup and tracking',
        'Performance analysis',
        'Data-driven optimization',
      ],
      frameworks: [
        { name: 'Content Metrics Framework', link: '/frameworks/content-metrics' },
        { name: 'Analytics Dashboard Setup', link: '/frameworks/analytics-setup' },
        { name: 'Performance Analysis Guide', link: '/frameworks/performance-analysis' },
      ],
      prerequisites: ['Content Repurposing'],
    },
    {
      id: 'calendar',
      title: 'Editorial Calendar',
      subtitle: 'Planning · Scheduling · Workflow',
      x: 250,
      y: 840,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Build and manage an editorial calendar for consistent content publication.',
      whatYouLearn: [
        'Editorial calendar design',
        'Content scheduling strategy',
        'Team workflow management',
        'Publication consistency',
      ],
      frameworks: [
        { name: 'Editorial Calendar Template', link: '/frameworks/editorial-calendar' },
        { name: 'Content Planning System', link: '/frameworks/content-planning' },
        { name: 'Workflow Management Guide', link: '/frameworks/workflow-management' },
      ],
      prerequisites: ['Content Analytics'],
    },
    {
      id: 'scaling',
      title: 'Scaling Content',
      subtitle: 'Systems · Team · Automation',
      x: 250,
      y: 960,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Scale content production through systems, team building, and automation.',
      whatYouLearn: [
        'Content system architecture',
        'Building content teams',
        'Automation opportunities',
        'Maintaining quality at scale',
      ],
      frameworks: [
        { name: 'Content Scaling Playbook', link: '/frameworks/content-scaling' },
        { name: 'Team Building Guide', link: '/frameworks/team-building' },
        { name: 'Content Automation Framework', link: '/frameworks/content-automation' },
      ],
      prerequisites: ['Editorial Calendar'],
    },
    {
      id: 'complete',
      title: '🎉 MASTERY',
      x: 300,
      y: 1080,
      width: 200,
      height: 60,
      status: 'locked',
      description: 'Congratulations on completing the Content Marketing roadmap!',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: ['Scaling Content'],
    },
  ],

  connections: [
    { from: 'start', to: 'fundamentals', completed: true },
    { from: 'fundamentals', to: 'ideation', completed: true },
    { from: 'ideation', to: 'creation', completed: false },
    { from: 'ideation', to: 'seo', completed: false },
    { from: 'creation', to: 'distribution', completed: false },
    { from: 'seo', to: 'distribution', completed: false },
    { from: 'distribution', to: 'repurposing', completed: false },
    { from: 'repurposing', to: 'measurement', completed: false },
    { from: 'measurement', to: 'calendar', completed: false },
    { from: 'calendar', to: 'scaling', completed: false },
    { from: 'scaling', to: 'complete', completed: false },
  ],
}
