import { RoadmapData } from '../types'

export const developerMarketingRoadmap: RoadmapData = {
  slug: 'developer-marketing',
  title: 'Developer Marketing',
  description: 'Master the art of marketing to technical audiences through developer-centric content, community building, and authentic engagement.',
  icon: '👨‍💻',
  difficulty: 'intermediate',
  duration: '4-6 months',
  totalTopics: 14,
  
  nodes: [
    {
      id: 'start',
      title: 'START',
      x: 300,
      y: 20,
      width: 200,
      height: 60,
      status: 'completed',
      description: 'Begin your developer marketing journey',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'fundamentals',
      title: 'Developer Marketing Basics',
      subtitle: 'Audience · Psychology · Principles',
      x: 250,
      y: 120,
      width: 300,
      height: 80,
      status: 'completed',
      description: 'Understand the unique aspects of marketing to developers and technical audiences.',
      whatYouLearn: [
        'Developer persona characteristics',
        'How developers evaluate products',
        'Anti-patterns in developer marketing',
        'Building trust with technical audiences',
      ],
      frameworks: [
        { name: 'Developer Persona Framework', link: '/frameworks/developer-personas' },
        { name: 'Technical Audience Psychology', link: '/frameworks/technical-psychology' },
        { name: 'Developer Trust Model', link: '/frameworks/developer-trust' },
      ],
      prerequisites: [],
    },
    {
      id: 'product-positioning',
      title: 'Developer Product Positioning',
      subtitle: 'Value Props · Technical Messaging',
      x: 250,
      y: 240,
      width: 300,
      height: 80,
      status: 'in-progress',
      description: 'Position technical products with clear value propositions that resonate with developers.',
      whatYouLearn: [
        'Technical value proposition development',
        'Feature vs benefit for developers',
        'API-first messaging strategies',
        'Developer-centric positioning frameworks',
      ],
      frameworks: [
        { name: 'Technical Value Prop Canvas', link: '/frameworks/technical-value-prop' },
        { name: 'API Product Positioning', link: '/frameworks/api-positioning' },
        { name: 'Developer Messaging Framework', link: '/frameworks/dev-messaging' },
      ],
      prerequisites: ['Developer Marketing Basics'],
    },
    {
      id: 'documentation',
      title: 'Developer Documentation',
      subtitle: 'Docs · Guides · API References',
      x: 100,
      y: 360,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Create comprehensive, developer-friendly documentation that drives adoption.',
      whatYouLearn: [
        'Documentation architecture',
        'API reference best practices',
        'Tutorial and guide creation',
        'Interactive code examples',
      ],
      frameworks: [
        { name: 'Documentation Strategy Framework', link: '/frameworks/docs-strategy' },
        { name: 'API Documentation Guide', link: '/frameworks/api-docs' },
        { name: 'Tutorial Design System', link: '/frameworks/tutorial-design' },
      ],
      prerequisites: ['Developer Product Positioning'],
    },
    {
      id: 'content-strategy',
      title: 'Technical Content Strategy',
      subtitle: 'Blogs · Tutorials · Videos',
      x: 400,
      y: 360,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Develop content that educates, engages, and converts technical audiences.',
      whatYouLearn: [
        'Technical blog writing',
        'Code tutorial creation',
        'Video content for developers',
        'Content distribution strategies',
      ],
      frameworks: [
        { name: 'Technical Content Framework', link: '/frameworks/technical-content' },
        { name: 'Tutorial Creation Playbook', link: '/frameworks/tutorial-creation' },
        { name: 'Developer Content Distribution', link: '/frameworks/dev-content-distribution' },
      ],
      prerequisites: ['Developer Product Positioning'],
    },
    {
      id: 'community',
      title: 'Developer Community',
      subtitle: 'Forums · Discord · Open Source',
      x: 100,
      y: 480,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Build and nurture thriving developer communities around your product.',
      whatYouLearn: [
        'Community building strategies',
        'Forum and Discord management',
        'Open source community engagement',
        'Developer advocacy programs',
      ],
      frameworks: [
        { name: 'Community Building Framework', link: '/frameworks/community-building' },
        { name: 'Developer Advocacy Playbook', link: '/frameworks/developer-advocacy' },
        { name: 'Open Source Strategy', link: '/frameworks/open-source-strategy' },
      ],
      prerequisites: ['Developer Documentation'],
    },
    {
      id: 'devrel',
      title: 'Developer Relations',
      subtitle: 'Advocacy · Evangelism · Support',
      x: 400,
      y: 480,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Establish developer relations programs that build authentic relationships.',
      whatYouLearn: [
        'DevRel program structure',
        'Developer advocacy vs evangelism',
        'Technical support strategies',
        'Community feedback loops',
      ],
      frameworks: [
        { name: 'DevRel Framework', link: '/frameworks/devrel' },
        { name: 'Developer Advocacy Model', link: '/frameworks/dev-advocacy' },
        { name: 'Technical Support System', link: '/frameworks/tech-support' },
      ],
      prerequisites: ['Technical Content Strategy'],
    },
    {
      id: 'developer-experience',
      title: 'Developer Experience (DX)',
      subtitle: 'Onboarding · API Design · Tools',
      x: 250,
      y: 600,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Optimize the end-to-end developer experience from first touch to production.',
      whatYouLearn: [
        'DX assessment and optimization',
        'Developer onboarding design',
        'API and SDK user experience',
        'Developer tool ecosystem',
      ],
      frameworks: [
        { name: 'Developer Experience Framework', link: '/frameworks/dx-framework' },
        { name: 'API UX Principles', link: '/frameworks/api-ux' },
        { name: 'Onboarding Optimization', link: '/frameworks/dev-onboarding' },
      ],
      prerequisites: ['Developer Community', 'Developer Relations'],
    },
    {
      id: 'events',
      title: 'Developer Events & Conferences',
      subtitle: 'Hackathons · Meetups · Conferences',
      x: 250,
      y: 720,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Plan and execute developer events that build awareness and community.',
      whatYouLearn: [
        'Hackathon organization',
        'Developer meetup strategies',
        'Conference presence optimization',
        'Virtual event execution',
      ],
      frameworks: [
        { name: 'Developer Events Framework', link: '/frameworks/dev-events' },
        { name: 'Hackathon Playbook', link: '/frameworks/hackathons' },
        { name: 'Conference Strategy', link: '/frameworks/conference-strategy' },
      ],
      prerequisites: ['Developer Experience'],
    },
    {
      id: 'partnerships',
      title: 'Developer Partnerships',
      subtitle: 'Integrations · Ecosystem · Affiliates',
      x: 250,
      y: 840,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Build strategic partnerships and integration ecosystems.',
      whatYouLearn: [
        'Integration partnership strategy',
        'Developer ecosystem development',
        'Technical partnership marketing',
        'Co-marketing with tech brands',
      ],
      frameworks: [
        { name: 'Partnership Framework', link: '/frameworks/partnerships' },
        { name: 'Integration Ecosystem Model', link: '/frameworks/integration-ecosystem' },
        { name: 'Co-Marketing Playbook', link: '/frameworks/co-marketing' },
      ],
      prerequisites: ['Developer Events & Conferences'],
    },
    {
      id: 'metrics',
      title: 'Developer Marketing Metrics',
      subtitle: 'Adoption · Engagement · Attribution',
      x: 250,
      y: 960,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Measure developer marketing effectiveness with appropriate metrics.',
      whatYouLearn: [
        'Developer-specific KPIs',
        'API adoption metrics',
        'Community health indicators',
        'Attribution modeling for technical audiences',
      ],
      frameworks: [
        { name: 'Developer Metrics Framework', link: '/frameworks/dev-metrics' },
        { name: 'API Adoption Analytics', link: '/frameworks/api-analytics' },
        { name: 'Community Health Metrics', link: '/frameworks/community-metrics' },
      ],
      prerequisites: ['Developer Partnerships'],
    },
    {
      id: 'open-source',
      title: 'Open Source Marketing',
      subtitle: 'OSS Strategy · Contribution · Sponsorship',
      x: 100,
      y: 1080,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Leverage open source for developer marketing and community building.',
      whatYouLearn: [
        'Open source marketing strategy',
        'OSS contribution programs',
        'Sponsorship strategies',
        'Building credibility through OSS',
      ],
      frameworks: [
        { name: 'Open Source Marketing Framework', link: '/frameworks/oss-marketing' },
        { name: 'OSS Contribution Strategy', link: '/frameworks/oss-contribution' },
        { name: 'Sponsorship ROI Model', link: '/frameworks/sponsorship-roi' },
      ],
      prerequisites: ['Developer Marketing Metrics'],
    },
    {
      id: 'technical-seo',
      title: 'Technical SEO & Discovery',
      subtitle: 'Search · Discoverability · Rankings',
      x: 400,
      y: 1080,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Optimize for developer search behavior and technical content discovery.',
      whatYouLearn: [
        'Technical documentation SEO',
        'Developer search behavior',
        'Code snippet optimization',
        'API reference discoverability',
      ],
      frameworks: [
        { name: 'Technical SEO Framework', link: '/frameworks/technical-seo' },
        { name: 'Developer Search Strategy', link: '/frameworks/dev-search' },
        { name: 'Documentation SEO Guide', link: '/frameworks/docs-seo' },
      ],
      prerequisites: ['Developer Marketing Metrics'],
    },
    {
      id: 'product-led-growth',
      title: 'PLG for Developer Products',
      subtitle: 'Self-Serve · Viral Loops · Expansion',
      x: 250,
      y: 1200,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Implement product-led growth strategies for developer tools and APIs.',
      whatYouLearn: [
        'Self-serve adoption models',
        'Developer product virality',
        'Usage-based expansion',
        'Bottom-up enterprise adoption',
      ],
      frameworks: [
        { name: 'Developer PLG Framework', link: '/frameworks/dev-plg' },
        { name: 'API Virality Model', link: '/frameworks/api-virality' },
        { name: 'Bottom-Up Adoption Strategy', link: '/frameworks/bottom-up-adoption' },
      ],
      prerequisites: ['Open Source Marketing', 'Technical SEO & Discovery'],
    },
    {
      id: 'complete',
      title: '🎉 MASTERY',
      x: 300,
      y: 1320,
      width: 200,
      height: 60,
      status: 'locked',
      description: 'Congratulations on completing the Developer Marketing roadmap!',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: ['PLG for Developer Products'],
    },
  ],

  connections: [
    { from: 'start', to: 'fundamentals', completed: true },
    { from: 'fundamentals', to: 'product-positioning', completed: true },
    { from: 'product-positioning', to: 'documentation', completed: false },
    { from: 'product-positioning', to: 'content-strategy', completed: false },
    { from: 'documentation', to: 'community', completed: false },
    { from: 'content-strategy', to: 'devrel', completed: false },
    { from: 'community', to: 'developer-experience', completed: false },
    { from: 'devrel', to: 'developer-experience', completed: false },
    { from: 'developer-experience', to: 'events', completed: false },
    { from: 'events', to: 'partnerships', completed: false },
    { from: 'partnerships', to: 'metrics', completed: false },
    { from: 'metrics', to: 'open-source', completed: false },
    { from: 'metrics', to: 'technical-seo', completed: false },
    { from: 'open-source', to: 'product-led-growth', completed: false },
    { from: 'technical-seo', to: 'product-led-growth', completed: false },
    { from: 'product-led-growth', to: 'complete', completed: false },
  ],
}
