import { RoadmapData } from '../types'

export const growthMarketingRoadmap: RoadmapData = {
  slug: 'growth-marketing',
  title: 'Growth Marketing',
  description: 'Master data-driven growth strategies, experimentation frameworks, and scalable acquisition channels to drive sustainable business growth.',
  icon: '📈',
  difficulty: 'intermediate',
  duration: '4-6 months',
  totalTopics: 58,
  layout: 'horizontal-pillars',
  expandable: true,
  defaultView: 'contexts',
  
  nodes: [
    // ============================================
    // START NODE
    // ============================================
    {
      id: 'start',
      title: 'START HERE',
      x: 650,
      y: 30,
      width: 300,
      height: 55,
      status: 'completed',
      nodeType: 'pillar',
      description: 'Begin your growth marketing journey',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },

    // ============================================
    // PILLAR 1: ACQUISITION
    // ============================================
    {
      id: 'acquisition-pillar',
      title: 'ACQUISITION',
      x: 50,
      y: 150,
      width: 280,
      height: 55,
      status: 'completed',
      nodeType: 'pillar',
      category: 'Acquisition',
      description: 'Strategies and channels for acquiring new customers',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },

    // Context: Paid Acquisition
    {
      id: 'paid-acquisition-context',
      title: 'Paid Acquisition',
      x: 60,
      y: 255,
      width: 260,
      height: 45,
      status: 'completed',
      nodeType: 'context',
      category: 'Acquisition',
      description: 'Master paid advertising channels and profitably scale acquisition',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'cac-ltv',
      title: 'CAC/LTV Model',
      x: 70,
      y: 350,
      width: 240,
      height: 35,
      status: 'completed',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Master customer acquisition cost and lifetime value modeling',
      whatYouLearn: [
        'Calculate true CAC including all costs',
        'Model customer lifetime value',
        'Set healthy CAC:LTV ratios',
        'Payback period optimization',
      ],
      frameworks: [
        { name: 'CAC/LTV Framework', link: '/frameworks/cac-ltv' },
        { name: 'Unit Economics Model', link: '/frameworks/unit-economics' },
      ],
      prerequisites: [],
    },
    {
      id: 'attribution-modeling',
      title: 'Attribution Modeling',
      x: 70,
      y: 435,
      width: 240,
      height: 35,
      status: 'in-progress',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Understand which channels drive conversions',
      whatYouLearn: [
        'Multi-touch attribution models',
        'First-click vs last-click attribution',
        'Data-driven attribution',
        'Cross-device tracking',
      ],
      frameworks: [
        { name: 'Attribution Models Guide', link: '/frameworks/attribution-models' },
        { name: 'Marketing Mix Modeling', link: '/frameworks/marketing-mix' },
      ],
      prerequisites: ['CAC/LTV Model'],
    },
    {
      id: 'auction-theory',
      title: 'Auction Theory Basics',
      x: 70,
      y: 520,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Understand how ad auctions work to optimize bids',
      whatYouLearn: [
        'How ad auctions function',
        'Quality score impact on CPCs',
        'Bid optimization strategies',
        'Ad rank calculation',
      ],
      frameworks: [
        { name: 'Auction Theory Guide', link: '/frameworks/auction-theory' },
        { name: 'Bid Strategy Framework', link: '/frameworks/bid-strategy' },
      ],
      prerequisites: ['Attribution Modeling'],
    },
    {
      id: 'paid-tools',
      title: 'Paid Ad Platforms',
      subtitle: 'TOOLS & CHANNELS',
      x: 70,
      y: 585,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Acquisition',
      description: 'Major paid advertising platforms',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'Google Ads', sponsored: true, link: '#' },
        { name: 'Facebook Ads', sponsored: false, link: '#' },
        { name: 'LinkedIn Ads', sponsored: false, link: '#' },
        { name: 'TikTok Ads', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // Context: Organic Acquisition
    {
      id: 'organic-acquisition-context',
      title: 'Organic Acquisition',
      x: 60,
      y: 715,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Acquisition',
      description: 'Build sustainable growth through SEO and content',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'flywheels',
      title: 'Flywheels Framework',
      x: 70,
      y: 810,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Build self-reinforcing growth engines',
      whatYouLearn: [
        'Flywheel vs funnel thinking',
        'Identifying flywheel opportunities',
        'Momentum building tactics',
        'Measuring flywheel velocity',
      ],
      frameworks: [
        { name: 'Flywheels Framework', link: '/frameworks/flywheels' },
        { name: 'Momentum Metrics', link: '/frameworks/momentum-metrics' },
      ],
      prerequisites: [],
    },
    {
      id: 'content-moat',
      title: 'Content Moat Strategy',
      x: 70,
      y: 895,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Create defensible competitive advantages through content',
      whatYouLearn: [
        'Building content moats',
        'Compounding content assets',
        'Proprietary data content',
        'Authority building',
      ],
      frameworks: [
        { name: 'Content Moat Strategy', link: '/frameworks/content-moat' },
        { name: 'Content Authority Framework', link: '/frameworks/content-authority' },
      ],
      prerequisites: ['Flywheels Framework'],
    },
    {
      id: 'seo-value-chain',
      title: 'SEO Value Chain',
      x: 70,
      y: 980,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Systematic approach to SEO success',
      whatYouLearn: [
        'Technical SEO foundations',
        'On-page optimization',
        'Link building strategies',
        'Content-to-conversion optimization',
      ],
      frameworks: [
        { name: 'SEO Value Chain', link: '/frameworks/seo-value-chain' },
        { name: 'Technical SEO Checklist', link: '/frameworks/technical-seo' },
      ],
      prerequisites: ['Content Moat Strategy'],
    },
    {
      id: 'organic-tools',
      title: 'SEO & Content Tools',
      subtitle: 'TOOLS & CHANNELS',
      x: 70,
      y: 1045,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Acquisition',
      description: 'Essential SEO and content marketing tools',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'Ahrefs', sponsored: false, link: '#' },
        { name: 'SEMrush', sponsored: false, link: '#' },
        { name: 'Clearscope', sponsored: false, link: '#' },
        { name: 'Surfer SEO', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // Context: Partnership Acquisition
    {
      id: 'partnership-acquisition-context',
      title: 'Partnership Acquisition',
      x: 60,
      y: 1175,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Acquisition',
      description: 'Scale through strategic partnerships',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'channel-partner-economics',
      title: 'Channel Partner Economics',
      x: 70,
      y: 1270,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Design profitable partner programs',
      whatYouLearn: [
        'Partner commission structures',
        'Channel economics modeling',
        'Partner enablement',
        'Revenue sharing models',
      ],
      frameworks: [
        { name: 'Partner Economics Model', link: '/frameworks/partner-economics' },
        { name: 'Channel Program Design', link: '/frameworks/channel-program' },
      ],
      prerequisites: [],
    },
    {
      id: 'co-marketing',
      title: 'Co-Marketing Framework',
      x: 70,
      y: 1355,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Leverage partnerships for mutual growth',
      whatYouLearn: [
        'Co-marketing strategy',
        'Partner selection criteria',
        'Campaign collaboration',
        'Value exchange models',
      ],
      frameworks: [
        { name: 'Co-Marketing Playbook', link: '/frameworks/co-marketing' },
        { name: 'Partnership Value Framework', link: '/frameworks/partnership-value' },
      ],
      prerequisites: ['Channel Partner Economics'],
    },
    {
      id: 'affiliate-attribution',
      title: 'Affiliate Attribution Model',
      x: 70,
      y: 1440,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Acquisition',
      description: 'Track and attribute affiliate conversions',
      whatYouLearn: [
        'Affiliate tracking setup',
        'Cookie attribution',
        'Multi-touch affiliate credit',
        'Fraud prevention',
      ],
      frameworks: [
        { name: 'Affiliate Attribution', link: '/frameworks/affiliate-attribution' },
        { name: 'Affiliate Program Design', link: '/frameworks/affiliate-program' },
      ],
      prerequisites: ['Co-Marketing Framework'],
    },
    {
      id: 'partnership-tools',
      title: 'Partnership Platforms',
      subtitle: 'TOOLS & CHANNELS',
      x: 70,
      y: 1505,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Acquisition',
      description: 'Partnership and affiliate management platforms',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'Impact', sponsored: false, link: '#' },
        { name: 'PartnerStack', sponsored: false, link: '#' },
        { name: 'Rewardful', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // ============================================
    // PILLAR 2: ACTIVATION
    // ============================================
    {
      id: 'activation-pillar',
      title: 'ACTIVATION',
      x: 410,
      y: 150,
      width: 280,
      height: 55,
      status: 'locked',
      nodeType: 'pillar',
      category: 'Activation',
      description: 'Optimize user onboarding and time-to-value',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },

    // Context: Onboarding Strategy
    {
      id: 'onboarding-context',
      title: 'Onboarding Strategy',
      x: 420,
      y: 255,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Activation',
      description: 'Guide users to their first value moment',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'aha-moment',
      title: 'Aha Moment Framework',
      x: 430,
      y: 350,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Activation',
      description: 'Identify and optimize for your product\'s Aha Moment',
      whatYouLearn: [
        'Defining your Aha Moment',
        'Time-to-Aha optimization',
        'Activation metric selection',
        'Measuring activation success',
      ],
      frameworks: [
        { name: 'Aha Moment Framework', link: '/frameworks/aha-moment' },
        { name: 'Activation Metrics', link: '/frameworks/activation-metrics' },
      ],
      prerequisites: [],
    },
    {
      id: 'time-to-value',
      title: 'Time-to-Value Optimization',
      x: 430,
      y: 435,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Activation',
      description: 'Minimize time from signup to first value',
      whatYouLearn: [
        'TTV measurement',
        'Friction point identification',
        'Onboarding flow optimization',
        'Quick win strategies',
      ],
      frameworks: [
        { name: 'Time-to-Value Framework', link: '/frameworks/time-to-value' },
        { name: 'Friction Analysis', link: '/frameworks/friction-analysis' },
      ],
      prerequisites: ['Aha Moment Framework'],
    },
    {
      id: 'progressive-disclosure',
      title: 'Progressive Disclosure',
      x: 430,
      y: 520,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Activation',
      description: 'Reveal complexity gradually to prevent overwhelm',
      whatYouLearn: [
        'Information layering principles',
        'Feature introduction timing',
        'Cognitive load management',
        'Guided onboarding design',
      ],
      frameworks: [
        { name: 'Progressive Disclosure', link: '/frameworks/progressive-disclosure' },
        { name: 'Onboarding UX Patterns', link: '/frameworks/onboarding-ux' },
      ],
      prerequisites: ['Time-to-Value Optimization'],
    },
    {
      id: 'onboarding-tools',
      title: 'Onboarding Tools',
      subtitle: 'TOOLS & CHANNELS',
      x: 430,
      y: 585,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Activation',
      description: 'User onboarding and product tour platforms',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'Appcues', sponsored: false, link: '#' },
        { name: 'Pendo', sponsored: false, link: '#' },
        { name: 'Userflow', sponsored: false, link: '#' },
        { name: 'Chameleon', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // Context: Product Engagement
    {
      id: 'engagement-context',
      title: 'Product Engagement',
      x: 420,
      y: 715,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Activation',
      description: 'Build habit-forming product experiences',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'hook-model',
      title: 'Hook Model (Nir Eyal)',
      x: 430,
      y: 810,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Activation',
      description: 'Create habit-forming products',
      whatYouLearn: [
        'Trigger-Action-Reward-Investment cycle',
        'Internal vs external triggers',
        'Variable reward design',
        'Investment mechanics',
      ],
      frameworks: [
        { name: 'Hook Model Framework', link: '/frameworks/hook-model' },
        { name: 'Habit Formation Guide', link: '/frameworks/habit-formation' },
      ],
      prerequisites: [],
    },
    {
      id: 'behavioral-triggers',
      title: 'Behavioral Triggers',
      x: 430,
      y: 895,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Activation',
      description: 'Design triggers that prompt user action',
      whatYouLearn: [
        'Types of behavioral triggers',
        'Trigger timing optimization',
        'Multi-channel trigger design',
        'Trigger fatigue prevention',
      ],
      frameworks: [
        { name: 'Behavioral Triggers', link: '/frameworks/behavioral-triggers' },
        { name: 'Trigger Design Patterns', link: '/frameworks/trigger-patterns' },
      ],
      prerequisites: ['Hook Model (Nir Eyal)'],
    },
    {
      id: 'engagement-loops',
      title: 'Engagement Loops',
      x: 430,
      y: 980,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Activation',
      description: 'Build self-reinforcing engagement patterns',
      whatYouLearn: [
        'Core engagement loop design',
        'Notification strategies',
        'Streak mechanics',
        'Social engagement loops',
      ],
      frameworks: [
        { name: 'Engagement Loops', link: '/frameworks/engagement-loops' },
        { name: 'Gamification Framework', link: '/frameworks/gamification' },
      ],
      prerequisites: ['Behavioral Triggers'],
    },
    {
      id: 'engagement-tools',
      title: 'Analytics & Engagement',
      subtitle: 'TOOLS & CHANNELS',
      x: 430,
      y: 1045,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Activation',
      description: 'Product analytics and engagement platforms',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'Amplitude', sponsored: false, link: '#' },
        { name: 'Mixpanel', sponsored: false, link: '#' },
        { name: 'Heap', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // ============================================
    // PILLAR 3: RETENTION
    // ============================================
    {
      id: 'retention-pillar',
      title: 'RETENTION',
      x: 770,
      y: 150,
      width: 280,
      height: 55,
      status: 'locked',
      nodeType: 'pillar',
      category: 'Retention',
      description: 'Keep users engaged and reduce churn',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },

    // Context: Email & Messaging
    {
      id: 'messaging-context',
      title: 'Email & Messaging',
      x: 780,
      y: 255,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Retention',
      description: 'Lifecycle communication strategies',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'lifecycle-email',
      title: 'Lifecycle Email Sequencing',
      x: 790,
      y: 350,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Retention',
      description: 'Design automated email sequences for each lifecycle stage',
      whatYouLearn: [
        'Lifecycle segmentation',
        'Email sequence design',
        'Cadence optimization',
        'Personalization strategies',
      ],
      frameworks: [
        { name: 'Lifecycle Email Framework', link: '/frameworks/lifecycle-email' },
        { name: 'Email Segmentation', link: '/frameworks/email-segmentation' },
      ],
      prerequisites: [],
    },
    {
      id: 'triggered-messaging',
      title: 'Triggered Messaging Framework',
      x: 790,
      y: 435,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Retention',
      description: 'Send contextual messages based on user behavior',
      whatYouLearn: [
        'Event-based triggers',
        'Multi-channel messaging',
        'Trigger timing optimization',
        'Message prioritization',
      ],
      frameworks: [
        { name: 'Triggered Messaging', link: '/frameworks/triggered-messaging' },
        { name: 'Message Orchestration', link: '/frameworks/message-orchestration' },
      ],
      prerequisites: ['Lifecycle Email Sequencing'],
    },
    {
      id: 'reengagement-campaigns',
      title: 'Re-engagement Campaigns',
      x: 790,
      y: 520,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Retention',
      description: 'Win back inactive users',
      whatYouLearn: [
        'Dormancy detection',
        'Win-back sequence design',
        'Incentive strategies',
        'Resurrection metrics',
      ],
      frameworks: [
        { name: 'Re-engagement Playbook', link: '/frameworks/reengagement' },
        { name: 'Win-back Campaigns', link: '/frameworks/winback' },
      ],
      prerequisites: ['Triggered Messaging Framework'],
    },
    {
      id: 'messaging-tools',
      title: 'Email/Messaging Platforms',
      subtitle: 'TOOLS & CHANNELS',
      x: 790,
      y: 585,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Retention',
      description: 'Customer engagement and messaging platforms',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'Customer.io', sponsored: false, link: '#' },
        { name: 'Braze', sponsored: false, link: '#' },
        { name: 'Iterable', sponsored: false, link: '#' },
        { name: 'Klaviyo', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // Context: Retention Analytics
    {
      id: 'retention-analytics-context',
      title: 'Retention Analytics',
      x: 780,
      y: 715,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Retention',
      description: 'Measure and optimize retention',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'cohort-retention',
      title: 'Cohort Retention Curves',
      x: 790,
      y: 810,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Retention',
      description: 'Analyze retention by user cohort',
      whatYouLearn: [
        'Cohort analysis methodology',
        'Retention curve interpretation',
        'Cohort comparison',
        'Retention improvement tracking',
      ],
      frameworks: [
        { name: 'Cohort Analysis Guide', link: '/frameworks/cohort-analysis' },
        { name: 'Retention Metrics', link: '/frameworks/retention-metrics' },
      ],
      prerequisites: [],
    },
    {
      id: 'churn-prediction',
      title: 'Churn Prediction Models',
      x: 790,
      y: 895,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Retention',
      description: 'Identify at-risk users before they churn',
      whatYouLearn: [
        'Churn signals identification',
        'Predictive modeling basics',
        'Risk scoring',
        'Intervention strategies',
      ],
      frameworks: [
        { name: 'Churn Prediction', link: '/frameworks/churn-prediction' },
        { name: 'Customer Health Score', link: '/frameworks/health-score' },
      ],
      prerequisites: ['Cohort Retention Curves'],
    },
    {
      id: 'power-user-analysis',
      title: 'Power User Analysis',
      x: 790,
      y: 980,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Retention',
      description: 'Identify and learn from your best users',
      whatYouLearn: [
        'Power user identification',
        'Behavioral pattern analysis',
        'Feature adoption correlation',
        'Creating more power users',
      ],
      frameworks: [
        { name: 'Power User Framework', link: '/frameworks/power-user' },
        { name: 'User Segmentation', link: '/frameworks/user-segmentation' },
      ],
      prerequisites: ['Churn Prediction Models'],
    },
    {
      id: 'retention-analytics-tools',
      title: 'Analytics Platforms',
      subtitle: 'TOOLS & CHANNELS',
      x: 790,
      y: 1045,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Retention',
      description: 'Product and retention analytics tools',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'Amplitude', sponsored: false, link: '#' },
        { name: 'Mixpanel', sponsored: false, link: '#' },
        { name: 'June.so', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // ============================================
    // PILLAR 4: REVENUE
    // ============================================
    {
      id: 'revenue-pillar',
      title: 'REVENUE',
      x: 1130,
      y: 150,
      width: 280,
      height: 55,
      status: 'locked',
      nodeType: 'pillar',
      category: 'Revenue',
      description: 'Optimize monetization and expansion',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },

    // Context: Pricing Strategy
    {
      id: 'pricing-context',
      title: 'Pricing Strategy',
      x: 1140,
      y: 255,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Revenue',
      description: 'Optimize pricing and packaging',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'value-based-pricing',
      title: 'Value-Based Pricing',
      x: 1150,
      y: 350,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Revenue',
      description: 'Price based on customer value, not cost',
      whatYouLearn: [
        'Value metric selection',
        'Willingness-to-pay research',
        'Value communication',
        'Price anchoring',
      ],
      frameworks: [
        { name: 'Value-Based Pricing', link: '/frameworks/value-based-pricing' },
        { name: 'Pricing Strategy Canvas', link: '/frameworks/pricing-strategy' },
      ],
      prerequisites: [],
    },
    {
      id: 'price-sensitivity',
      title: 'Price Sensitivity Analysis',
      x: 1150,
      y: 435,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Revenue',
      description: 'Understand how price changes affect demand',
      whatYouLearn: [
        'Price elasticity measurement',
        'Van Westendorp analysis',
        'Conjoint analysis basics',
        'A/B pricing tests',
      ],
      frameworks: [
        { name: 'Price Sensitivity', link: '/frameworks/price-sensitivity' },
        { name: 'Pricing Research Methods', link: '/frameworks/pricing-research' },
      ],
      prerequisites: ['Value-Based Pricing'],
    },
    {
      id: 'packaging-tiering',
      title: 'Packaging & Tiering',
      x: 1150,
      y: 520,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Revenue',
      description: 'Design pricing tiers that drive upgrades',
      whatYouLearn: [
        'Good-Better-Best strategy',
        'Feature tiering',
        'Decoy pricing',
        'Tier migration paths',
      ],
      frameworks: [
        { name: 'Packaging Framework', link: '/frameworks/packaging' },
        { name: 'Tier Design Principles', link: '/frameworks/tier-design' },
      ],
      prerequisites: ['Price Sensitivity Analysis'],
    },
    {
      id: 'pricing-tools',
      title: 'Pricing & Revenue Tools',
      subtitle: 'TOOLS & CHANNELS',
      x: 1150,
      y: 585,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Revenue',
      description: 'Pricing optimization and revenue analytics',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'ProfitWell', sponsored: false, link: '#' },
        { name: 'Price Intelligently', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // Context: Expansion Revenue
    {
      id: 'expansion-context',
      title: 'Expansion Revenue',
      x: 1140,
      y: 715,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Revenue',
      description: 'Grow revenue from existing customers',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'upsell-crosssell',
      title: 'Upsell/Cross-sell Framework',
      x: 1150,
      y: 810,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Revenue',
      description: 'Drive expansion through upsells and cross-sells',
      whatYouLearn: [
        'Expansion opportunity identification',
        'Upsell timing and triggers',
        'Cross-sell recommendations',
        'Expansion playbooks',
      ],
      frameworks: [
        { name: 'Upsell Framework', link: '/frameworks/upsell' },
        { name: 'Cross-sell Strategy', link: '/frameworks/crosssell' },
      ],
      prerequisites: [],
    },
    {
      id: 'net-revenue-retention',
      title: 'Net Revenue Retention',
      x: 1150,
      y: 895,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Revenue',
      description: 'Measure and optimize revenue from existing customers',
      whatYouLearn: [
        'NRR calculation and benchmarks',
        'Expansion vs contraction',
        'Cohort-based NRR analysis',
        'NRR improvement levers',
      ],
      frameworks: [
        { name: 'NRR Framework', link: '/frameworks/net-revenue-retention' },
        { name: 'Revenue Retention Metrics', link: '/frameworks/revenue-retention' },
      ],
      prerequisites: ['Upsell/Cross-sell Framework'],
    },
    {
      id: 'account-expansion',
      title: 'Account Expansion Plays',
      x: 1150,
      y: 980,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Revenue',
      description: 'Systematic account growth strategies',
      whatYouLearn: [
        'Land and expand strategy',
        'Multi-product adoption',
        'Seat expansion tactics',
        'Account-based expansion',
      ],
      frameworks: [
        { name: 'Account Expansion', link: '/frameworks/account-expansion' },
        { name: 'Land and Expand', link: '/frameworks/land-expand' },
      ],
      prerequisites: ['Net Revenue Retention'],
    },
    {
      id: 'expansion-tools',
      title: 'Revenue Analytics',
      subtitle: 'TOOLS & CHANNELS',
      x: 1150,
      y: 1045,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Revenue',
      description: 'Subscription and revenue analytics platforms',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'ChartMogul', sponsored: false, link: '#' },
        { name: 'Baremetrics', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // ============================================
    // PILLAR 5: REFERRAL (SMALLER)
    // ============================================
    {
      id: 'referral-pillar',
      title: 'REFERRAL',
      x: 50,
      y: 1635,
      width: 280,
      height: 55,
      status: 'locked',
      nodeType: 'pillar',
      category: 'Referral',
      description: 'Drive viral and referral growth',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'referral-context',
      title: 'Viral & Referral Programs',
      x: 60,
      y: 1740,
      width: 260,
      height: 45,
      status: 'locked',
      nodeType: 'context',
      category: 'Referral',
      description: 'Build programs that turn users into advocates',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'viral-coefficient',
      title: 'Viral Coefficient Model',
      x: 70,
      y: 1835,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Referral',
      description: 'Measure and optimize viral growth',
      whatYouLearn: [
        'K-factor calculation',
        'Viral cycle time',
        'Viral loop mechanics',
        'Virality optimization',
      ],
      frameworks: [
        { name: 'Viral Coefficient', link: '/frameworks/viral-coefficient' },
        { name: 'Viral Mechanics', link: '/frameworks/viral-mechanics' },
      ],
      prerequisites: [],
    },
    {
      id: 'referral-loop-design',
      title: 'Referral Loop Design',
      x: 70,
      y: 1920,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Referral',
      description: 'Design referral programs that work',
      whatYouLearn: [
        'Incentive structure design',
        'Double-sided incentives',
        'Sharing mechanics',
        'Attribution tracking',
      ],
      frameworks: [
        { name: 'Referral Program Design', link: '/frameworks/referral-design' },
        { name: 'Incentive Optimization', link: '/frameworks/incentive-optimization' },
      ],
      prerequisites: ['Viral Coefficient Model'],
    },
    {
      id: 'ambassador-programs',
      title: 'Ambassador Programs',
      x: 70,
      y: 2005,
      width: 240,
      height: 35,
      status: 'locked',
      nodeType: 'framework',
      category: 'Referral',
      description: 'Build communities of brand advocates',
      whatYouLearn: [
        'Ambassador program structure',
        'Community activation',
        'Advocate rewards',
        'Word-of-mouth amplification',
      ],
      frameworks: [
        { name: 'Ambassador Programs', link: '/frameworks/ambassador-programs' },
        { name: 'Community Advocacy', link: '/frameworks/community-advocacy' },
      ],
      prerequisites: ['Referral Loop Design'],
    },
    {
      id: 'referral-tools',
      title: 'Referral Platforms',
      subtitle: 'TOOLS & CHANNELS',
      x: 70,
      y: 2070,
      width: 240,
      height: 30,
      status: 'locked',
      nodeType: 'tool',
      category: 'Referral',
      description: 'Referral program management platforms',
      whatYouLearn: [],
      frameworks: [],
      tools: [
        { name: 'Viral Loops', sponsored: false, link: '#' },
        { name: 'ReferralCandy', sponsored: false, link: '#' },
        { name: 'Friendbuy', sponsored: false, link: '#' },
      ],
      prerequisites: [],
    },

    // ============================================
    // CROSS-CONTEXT FRAMEWORKS (HORIZONTAL BARS)
    // ============================================
    {
      id: 'north-star-metric',
      title: 'North Star Metric Framework',
      x: 200,
      y: 2250,
      width: 1000,
      height: 50,
      status: 'locked',
      nodeType: 'cross-context',
      description: 'Identify the one metric that matters most',
      whatYouLearn: [
        'Defining your North Star',
        'Input metrics identification',
        'Aligning teams around NSM',
        'NSM evolution over time',
      ],
      frameworks: [
        { name: 'North Star Metric', link: '/frameworks/north-star-metric' },
        { name: 'Input Metrics Framework', link: '/frameworks/input-metrics' },
      ],
      prerequisites: [],
    },
    {
      id: 'aarrr-pirate-metrics',
      title: 'AARRR / Pirate Metrics',
      x: 200,
      y: 2350,
      width: 1000,
      height: 50,
      status: 'locked',
      nodeType: 'cross-context',
      description: 'Framework for the entire growth funnel',
      whatYouLearn: [
        'AARRR framework deep-dive',
        'Metrics for each stage',
        'Funnel optimization',
        'Stage-specific strategies',
      ],
      frameworks: [
        { name: 'AARRR Framework', link: '/frameworks/aarrr' },
        { name: 'Funnel Analytics', link: '/frameworks/funnel-analytics' },
      ],
      prerequisites: [],
    },
    {
      id: 'growth-accounting',
      title: 'Growth Accounting Framework',
      x: 200,
      y: 2450,
      width: 1000,
      height: 50,
      status: 'locked',
      nodeType: 'cross-context',
      description: 'Decompose growth into its components',
      whatYouLearn: [
        'New + Retained + Resurrected - Churned',
        'Growth decomposition',
        'Quick ratio calculation',
        'Sustainable growth diagnosis',
      ],
      frameworks: [
        { name: 'Growth Accounting', link: '/frameworks/growth-accounting' },
        { name: 'Quick Ratio Analysis', link: '/frameworks/quick-ratio' },
      ],
      prerequisites: [],
    },
    {
      id: 'ice-scoring',
      title: 'ICE Scoring Framework (Impact, Confidence, Ease)',
      x: 200,
      y: 2550,
      width: 1000,
      height: 50,
      status: 'locked',
      nodeType: 'cross-context',
      description: 'Prioritize growth experiments and initiatives',
      whatYouLearn: [
        'ICE scoring methodology',
        'Prioritization frameworks',
        'Backlog management',
        'Resource allocation',
      ],
      frameworks: [
        { name: 'ICE Scoring', link: '/frameworks/ice-scoring' },
        { name: 'Experiment Prioritization', link: '/frameworks/experiment-prioritization' },
      ],
      prerequisites: [],
    },
    {
      id: 'experiment-design',
      title: 'Experiment Design Framework',
      x: 200,
      y: 2650,
      width: 1000,
      height: 50,
      status: 'locked',
      nodeType: 'cross-context',
      description: 'Design rigorous growth experiments',
      whatYouLearn: [
        'Hypothesis formation',
        'Experiment design principles',
        'Statistical significance',
        'Test analysis and iteration',
      ],
      frameworks: [
        { name: 'Experiment Design', link: '/frameworks/experiment-design' },
        { name: 'A/B Testing Guide', link: '/frameworks/ab-testing' },
        { name: 'Statistical Analysis', link: '/frameworks/statistical-analysis' },
      ],
      prerequisites: [],
    },

    // ============================================
    // MASTERY NODE
    // ============================================
    {
      id: 'complete',
      title: '🎉 GROWTH MARKETING MASTERY',
      x: 450,
      y: 2850,
      width: 500,
      height: 80,
      status: 'locked',
      nodeType: 'pillar',
      description: 'Congratulations! You now have a complete understanding of growth marketing from first principles to advanced tactics across all five pillars: Acquisition, Activation, Retention, Revenue, and Referral.',
      whatYouLearn: [
        'Complete growth marketing framework mastery',
        'Ability to diagnose and solve any growth challenge',
        'Data-driven decision making expertise',
        'Strategic thinking across the full customer lifecycle',
        'Cross-functional growth leadership',
      ],
      frameworks: [],
      prerequisites: ['North Star Metric Framework', 'AARRR / Pirate Metrics', 'Growth Accounting Framework', 'ICE Scoring Framework', 'Experiment Design Framework'],
    },
  ],

  connections: [
    // Start to Pillars
    { from: 'start', to: 'acquisition-pillar', completed: true },
    { from: 'start', to: 'activation-pillar', completed: false },
    { from: 'start', to: 'retention-pillar', completed: false },
    { from: 'start', to: 'revenue-pillar', completed: false },
    
    // ACQUISITION PILLAR
    { from: 'acquisition-pillar', to: 'paid-acquisition-context', completed: true },
    { from: 'acquisition-pillar', to: 'organic-acquisition-context', completed: false },
    { from: 'acquisition-pillar', to: 'partnership-acquisition-context', completed: false },
    
    // Paid Acquisition flow
    { from: 'paid-acquisition-context', to: 'cac-ltv', completed: true },
    { from: 'cac-ltv', to: 'attribution-modeling', completed: true },
    { from: 'attribution-modeling', to: 'auction-theory', completed: false },
    { from: 'auction-theory', to: 'paid-tools', completed: false },
    
    // Organic Acquisition flow
    { from: 'organic-acquisition-context', to: 'flywheels', completed: false },
    { from: 'flywheels', to: 'content-moat', completed: false },
    { from: 'content-moat', to: 'seo-value-chain', completed: false },
    { from: 'seo-value-chain', to: 'organic-tools', completed: false },
    
    // Partnership Acquisition flow
    { from: 'partnership-acquisition-context', to: 'channel-partner-economics', completed: false },
    { from: 'channel-partner-economics', to: 'co-marketing', completed: false },
    { from: 'co-marketing', to: 'affiliate-attribution', completed: false },
    { from: 'affiliate-attribution', to: 'partnership-tools', completed: false },
    
    // ACTIVATION PILLAR
    { from: 'activation-pillar', to: 'onboarding-context', completed: false },
    { from: 'activation-pillar', to: 'engagement-context', completed: false },
    
    // Onboarding flow
    { from: 'onboarding-context', to: 'aha-moment', completed: false },
    { from: 'aha-moment', to: 'time-to-value', completed: false },
    { from: 'time-to-value', to: 'progressive-disclosure', completed: false },
    { from: 'progressive-disclosure', to: 'onboarding-tools', completed: false },
    
    // Engagement flow
    { from: 'engagement-context', to: 'hook-model', completed: false },
    { from: 'hook-model', to: 'behavioral-triggers', completed: false },
    { from: 'behavioral-triggers', to: 'engagement-loops', completed: false },
    { from: 'engagement-loops', to: 'engagement-tools', completed: false },
    
    // RETENTION PILLAR
    { from: 'retention-pillar', to: 'messaging-context', completed: false },
    { from: 'retention-pillar', to: 'retention-analytics-context', completed: false },
    
    // Messaging flow
    { from: 'messaging-context', to: 'lifecycle-email', completed: false },
    { from: 'lifecycle-email', to: 'triggered-messaging', completed: false },
    { from: 'triggered-messaging', to: 'reengagement-campaigns', completed: false },
    { from: 'reengagement-campaigns', to: 'messaging-tools', completed: false },
    
    // Retention Analytics flow
    { from: 'retention-analytics-context', to: 'cohort-retention', completed: false },
    { from: 'cohort-retention', to: 'churn-prediction', completed: false },
    { from: 'churn-prediction', to: 'power-user-analysis', completed: false },
    { from: 'power-user-analysis', to: 'retention-analytics-tools', completed: false },
    
    // REVENUE PILLAR
    { from: 'revenue-pillar', to: 'pricing-context', completed: false },
    { from: 'revenue-pillar', to: 'expansion-context', completed: false },
    
    // Pricing flow
    { from: 'pricing-context', to: 'value-based-pricing', completed: false },
    { from: 'value-based-pricing', to: 'price-sensitivity', completed: false },
    { from: 'price-sensitivity', to: 'packaging-tiering', completed: false },
    { from: 'packaging-tiering', to: 'pricing-tools', completed: false },
    
    // Expansion flow
    { from: 'expansion-context', to: 'upsell-crosssell', completed: false },
    { from: 'upsell-crosssell', to: 'net-revenue-retention', completed: false },
    { from: 'net-revenue-retention', to: 'account-expansion', completed: false },
    { from: 'account-expansion', to: 'expansion-tools', completed: false },
    
    // REFERRAL PILLAR
    { from: 'start', to: 'referral-pillar', completed: false },
    { from: 'referral-pillar', to: 'referral-context', completed: false },
    { from: 'referral-context', to: 'viral-coefficient', completed: false },
    { from: 'viral-coefficient', to: 'referral-loop-design', completed: false },
    { from: 'referral-loop-design', to: 'ambassador-programs', completed: false },
    { from: 'ambassador-programs', to: 'referral-tools', completed: false },
    
    // Cross-pillar connections to Cross-context frameworks
    { from: 'paid-tools', to: 'north-star-metric', completed: false, type: 'cross-context' },
    { from: 'organic-tools', to: 'north-star-metric', completed: false, type: 'cross-context' },
    { from: 'partnership-tools', to: 'north-star-metric', completed: false, type: 'cross-context' },
    { from: 'onboarding-tools', to: 'aarrr-pirate-metrics', completed: false, type: 'cross-context' },
    { from: 'engagement-tools', to: 'aarrr-pirate-metrics', completed: false, type: 'cross-context' },
    { from: 'messaging-tools', to: 'growth-accounting', completed: false, type: 'cross-context' },
    { from: 'retention-analytics-tools', to: 'growth-accounting', completed: false, type: 'cross-context' },
    { from: 'pricing-tools', to: 'ice-scoring', completed: false, type: 'cross-context' },
    { from: 'expansion-tools', to: 'ice-scoring', completed: false, type: 'cross-context' },
    { from: 'referral-tools', to: 'experiment-design', completed: false, type: 'cross-context' },
    
    // Cross-context frameworks to Mastery
    { from: 'north-star-metric', to: 'complete', completed: false },
    { from: 'aarrr-pirate-metrics', to: 'complete', completed: false },
    { from: 'growth-accounting', to: 'complete', completed: false },
    { from: 'ice-scoring', to: 'complete', completed: false },
    { from: 'experiment-design', to: 'complete', completed: false },
  ],
}