import { RoadmapData } from '../types'

export const growthMarketingRoadmap: RoadmapData = {
  slug: 'growth-marketing',
  title: 'Growth Marketing',
  description: 'Master data-driven growth strategies, experimentation frameworks, and scalable acquisition channels to drive sustainable business growth.',
  icon: '📈',
  difficulty: 'intermediate',
  duration: '4-6 months',
  totalTopics: 12,
  
  nodes: [
    {
      id: 'start',
      title: 'START',
      x: 300,
      y: 20,
      width: 200,
      height: 60,
      status: 'completed',
      description: 'Begin your growth marketing journey',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'fundamentals',
      title: 'Marketing Fundamentals',
      subtitle: 'First Principles · Customer Psychology',
      x: 250,
      y: 140,
      width: 300,
      height: 80,
      status: 'completed',
      description: 'Build a strong foundation in marketing first principles and understand customer psychology to inform all your growth initiatives.',
      whatYouLearn: [
        'Marketing first principles and core concepts',
        'Customer psychology and decision-making',
        'Value creation and communication',
        'Understanding customer jobs-to-be-done',
      ],
      frameworks: [
        { name: 'Marketing First Principles', link: '/frameworks/marketing-first-principles' },
        { name: 'Jobs-to-be-Done', link: '/frameworks/jobs-to-be-done' },
        { name: 'Value Proposition Canvas', link: '/frameworks/value-proposition-canvas' },
      ],
      prerequisites: [],
    },
    {
      id: 'analytics',
      title: 'Data & Analytics Foundations',
      subtitle: 'Metrics · Attribution · Experimentation',
      x: 250,
      y: 280,
      width: 300,
      height: 80,
      status: 'completed',
      description: 'Master the metrics, attribution models, and experimentation basics that power data-driven growth decisions.',
      whatYouLearn: [
        'Key growth metrics and KPIs',
        'Attribution modeling fundamentals',
        'Basic statistical concepts',
        'Setting up analytics infrastructure',
      ],
      frameworks: [
        { name: 'AARRR Pirate Metrics', link: '/frameworks/aarrr-metrics' },
        { name: 'North Star Metric', link: '/frameworks/north-star-metric' },
        { name: 'Attribution Models', link: '/frameworks/attribution-models' },
      ],
      prerequisites: ['Marketing Fundamentals'],
    },
    {
      id: 'organic',
      title: 'Organic Growth Channels',
      subtitle: 'SEO · Content · Community',
      x: 100,
      y: 420,
      width: 300,
      height: 80,
      status: 'in-progress',
      description: 'Master sustainable, cost-effective growth through SEO, content marketing, and community building. Learn to create compounding assets.',
      whatYouLearn: [
        'SEO fundamentals and technical optimization',
        'Content strategy and distribution systems',
        'Community-driven growth mechanics',
        'Measuring organic channel performance',
      ],
      frameworks: [
        { name: 'Content Marketing System', link: '/frameworks/content-marketing-system' },
        { name: 'SEO Strategy Canvas', link: '/frameworks/seo-strategy' },
        { name: 'Community Building Playbook', link: '/frameworks/community-building' },
      ],
      prerequisites: ['Marketing Fundamentals', 'Data & Analytics Foundations'],
    },
    {
      id: 'paid',
      title: 'Paid Acquisition',
      subtitle: 'PPC · Social Ads · Display',
      x: 400,
      y: 420,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Learn to profitably scale paid acquisition channels across search, social, and display advertising.',
      whatYouLearn: [
        'PPC campaign structure and optimization',
        'Social advertising best practices',
        'Creative testing and iteration',
        'Budget management and ROAS optimization',
      ],
      frameworks: [
        { name: 'Paid Channel Strategy', link: '/frameworks/paid-channel-strategy' },
        { name: 'ROAS Optimization Framework', link: '/frameworks/roas-optimization' },
        { name: 'Creative Testing Framework', link: '/frameworks/creative-testing' },
      ],
      prerequisites: ['Marketing Fundamentals', 'Data & Analytics Foundations'],
    },
    {
      id: 'frameworks',
      title: 'Growth Frameworks',
      subtitle: 'AARRR · Loops · North Star',
      x: 100,
      y: 560,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Apply proven growth frameworks to systematize your growth process and identify high-leverage opportunities.',
      whatYouLearn: [
        'AARRR framework deep-dive',
        'Designing effective growth loops',
        'Identifying your North Star Metric',
        'ICE scoring for prioritization',
      ],
      frameworks: [
        { name: 'Growth Loops Framework', link: '/frameworks/growth-loops' },
        { name: 'ICE Scoring Method', link: '/frameworks/ice-scoring' },
        { name: 'Growth Model Canvas', link: '/frameworks/growth-model-canvas' },
      ],
      prerequisites: ['Organic Growth Channels'],
    },
    {
      id: 'plg',
      title: 'Product-Led Growth',
      subtitle: 'Onboarding · Activation · Viral',
      x: 400,
      y: 560,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Drive growth through product excellence with optimized onboarding, activation strategies, and viral mechanics.',
      whatYouLearn: [
        'PLG fundamentals and strategy',
        'User onboarding optimization',
        'Activation metric identification',
        'Building viral product features',
      ],
      frameworks: [
        { name: 'Product-Led Growth Playbook', link: '/frameworks/plg-playbook' },
        { name: 'Onboarding Optimization', link: '/frameworks/onboarding-optimization' },
        { name: 'Viral Mechanics Framework', link: '/frameworks/viral-mechanics' },
      ],
      prerequisites: ['Paid Acquisition'],
    },
    {
      id: 'experimentation',
      title: 'Experimentation & Testing',
      subtitle: 'A/B Testing · Statistical Significance',
      x: 100,
      y: 700,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Master the science of experimentation to make data-driven decisions and continuously improve performance.',
      whatYouLearn: [
        'Experiment design and methodology',
        'Statistical significance and sample size',
        'A/B and multivariate testing',
        'Building an experimentation culture',
      ],
      frameworks: [
        { name: 'Experimentation Framework', link: '/frameworks/experimentation' },
        { name: 'Test Prioritization Matrix', link: '/frameworks/test-prioritization' },
        { name: 'Statistical Analysis Guide', link: '/frameworks/statistical-analysis' },
      ],
      prerequisites: ['Growth Frameworks'],
    },
    {
      id: 'automation',
      title: 'Marketing Automation',
      subtitle: 'Email · Workflows · Lead Scoring',
      x: 400,
      y: 700,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Implement marketing automation to scale personalized communication and improve conversion efficiency.',
      whatYouLearn: [
        'Email marketing automation',
        'Workflow design and optimization',
        'Lead scoring methodology',
        'Marketing automation platforms',
      ],
      frameworks: [
        { name: 'Email Automation Playbook', link: '/frameworks/email-automation' },
        { name: 'Lead Scoring Framework', link: '/frameworks/lead-scoring' },
        { name: 'Workflow Optimization', link: '/frameworks/workflow-optimization' },
      ],
      prerequisites: ['Product-Led Growth'],
    },
    {
      id: 'cro',
      title: 'Conversion Optimization',
      subtitle: 'Landing Pages · UX · Psychology',
      x: 250,
      y: 840,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Systematically improve conversion rates through psychology-driven optimization and rigorous testing.',
      whatYouLearn: [
        'Conversion psychology principles',
        'Landing page optimization',
        'UX best practices for conversion',
        'Funnel analysis and improvement',
      ],
      frameworks: [
        { name: 'CRO Framework', link: '/frameworks/cro-framework' },
        { name: 'Landing Page Optimization', link: '/frameworks/landing-page-optimization' },
        { name: 'Conversion Psychology', link: '/frameworks/conversion-psychology' },
      ],
      prerequisites: ['Experimentation & Testing', 'Marketing Automation'],
    },
    {
      id: 'retention',
      title: 'Retention & Engagement',
      subtitle: 'Cohort Analysis · Lifecycle Marketing',
      x: 250,
      y: 980,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Build strategies to keep users engaged, reduce churn, and maximize customer lifetime value.',
      whatYouLearn: [
        'Cohort analysis and retention metrics',
        'Lifecycle marketing strategies',
        'Churn reduction tactics',
        'Engagement scoring and segmentation',
      ],
      frameworks: [
        { name: 'Retention Framework', link: '/frameworks/retention-framework' },
        { name: 'Lifecycle Marketing Model', link: '/frameworks/lifecycle-marketing' },
        { name: 'Cohort Analysis Guide', link: '/frameworks/cohort-analysis' },
      ],
      prerequisites: ['Conversion Optimization'],
    },
    {
      id: 'advanced',
      title: 'Advanced Growth Tactics',
      subtitle: 'Viral Mechanics · Referrals · Network Effects',
      x: 250,
      y: 1120,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Master advanced growth tactics including viral mechanics, referral programs, and network effects.',
      whatYouLearn: [
        'Viral coefficient optimization',
        'Referral program design',
        'Network effects strategies',
        'Growth at scale challenges',
      ],
      frameworks: [
        { name: 'Viral Growth Playbook', link: '/frameworks/viral-growth' },
        { name: 'Referral Program Framework', link: '/frameworks/referral-programs' },
        { name: 'Network Effects Strategy', link: '/frameworks/network-effects' },
      ],
      prerequisites: ['Retention & Engagement'],
    },
    {
      id: 'complete',
      title: '🎉 MASTERY',
      x: 300,
      y: 1260,
      width: 200,
      height: 60,
      status: 'locked',
      description: 'Congratulations on completing the Growth Marketing roadmap!',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: ['Advanced Growth Tactics'],
    },
  ],

  connections: [
    { from: 'start', to: 'fundamentals', completed: true },
    { from: 'fundamentals', to: 'analytics', completed: true },
    { from: 'analytics', to: 'organic', completed: true },
    { from: 'analytics', to: 'paid', completed: false },
    { from: 'organic', to: 'frameworks', completed: false },
    { from: 'paid', to: 'plg', completed: false },
    { from: 'frameworks', to: 'experimentation', completed: false },
    { from: 'plg', to: 'automation', completed: false },
    { from: 'experimentation', to: 'cro', completed: false },
    { from: 'automation', to: 'cro', completed: false },
    { from: 'cro', to: 'retention', completed: false },
    { from: 'retention', to: 'advanced', completed: false },
    { from: 'advanced', to: 'complete', completed: false },
  ],
}
