import { RoadmapData } from '../types'

export const productMarketingRoadmap: RoadmapData = {
  slug: 'product-marketing',
  title: 'Product Marketing',
  description: 'Position products effectively, craft compelling messaging, and drive product-led growth.',
  icon: '🎯',
  difficulty: 'intermediate',
  duration: '4-7 months',
  totalTopics: 13,
  
  nodes: [
    {
      id: 'start',
      title: 'START',
      x: 300,
      y: 20,
      width: 200,
      height: 60,
      status: 'completed',
      description: 'Begin your product marketing journey',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: [],
    },
    {
      id: 'market-research',
      title: 'Market Research',
      subtitle: 'TAM/SAM/SOM · Competitive Analysis',
      x: 250,
      y: 120,
      width: 300,
      height: 80,
      status: 'completed',
      description: 'Understand your market size, competitive landscape, and positioning opportunities.',
      whatYouLearn: [
        'Market sizing (TAM/SAM/SOM)',
        'Competitive analysis frameworks',
        'Market trends identification',
        'White space opportunity mapping',
      ],
      frameworks: [
        { name: 'Market Sizing Framework', link: '/frameworks/market-sizing' },
        { name: 'Competitive Analysis Canvas', link: '/frameworks/competitive-analysis' },
        { name: 'Market Opportunity Assessment', link: '/frameworks/market-opportunity' },
      ],
      prerequisites: [],
    },
    {
      id: 'customer-research',
      title: 'Customer Research',
      subtitle: 'JTBD · Pain Points · Use Cases',
      x: 250,
      y: 240,
      width: 300,
      height: 80,
      status: 'in-progress',
      description: 'Deep understanding of customer jobs-to-be-done, pain points, and primary use cases.',
      whatYouLearn: [
        'Jobs-to-be-Done methodology',
        'Customer interview techniques',
        'Pain point prioritization',
        'Use case mapping',
      ],
      frameworks: [
        { name: 'Jobs-to-be-Done Framework', link: '/frameworks/jtbd' },
        { name: 'Customer Interview Guide', link: '/frameworks/customer-interviews' },
        { name: 'Pain Point Analysis', link: '/frameworks/pain-point-analysis' },
      ],
      prerequisites: ['Market Research'],
    },
    {
      id: 'positioning',
      title: 'Product Positioning',
      subtitle: 'Differentiation · Category · Story',
      x: 250,
      y: 360,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Craft distinctive positioning that differentiates your product in the market.',
      whatYouLearn: [
        'Positioning statement development',
        'Category creation vs competition',
        'Differentiation strategy',
        'Positioning testing methods',
      ],
      frameworks: [
        { name: 'Positioning Canvas', link: '/frameworks/positioning-canvas' },
        { name: 'Category Design Framework', link: '/frameworks/category-design' },
        { name: 'Differentiation Matrix', link: '/frameworks/differentiation-matrix' },
      ],
      prerequisites: ['Customer Research'],
    },
    {
      id: 'messaging',
      title: 'Messaging Framework',
      subtitle: 'Value Props · Benefits · Proof',
      x: 250,
      y: 480,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Create compelling messaging that communicates value clearly to target audiences.',
      whatYouLearn: [
        'Value proposition development',
        'Feature-benefit translation',
        'Message hierarchy design',
        'Proof point selection',
      ],
      frameworks: [
        { name: 'Messaging House', link: '/frameworks/messaging-house' },
        { name: 'Value Proposition Canvas', link: '/frameworks/value-prop-canvas' },
        { name: 'Message Testing Framework', link: '/frameworks/message-testing' },
      ],
      prerequisites: ['Product Positioning'],
    },
    {
      id: 'persona',
      title: 'Buyer Personas',
      subtitle: 'Segments · Motivations · Journey',
      x: 100,
      y: 600,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Develop detailed buyer personas and map their decision-making journey.',
      whatYouLearn: [
        'Persona development methodology',
        'Buyer motivation mapping',
        'Decision criteria analysis',
        'Buying committee dynamics',
      ],
      frameworks: [
        { name: 'Buyer Persona Template', link: '/frameworks/buyer-personas' },
        { name: 'Buying Committee Map', link: '/frameworks/buying-committee' },
        { name: 'Decision Journey Framework', link: '/frameworks/decision-journey' },
      ],
      prerequisites: ['Messaging Framework'],
    },
    {
      id: 'launch',
      title: 'Product Launch',
      subtitle: 'GTM · Tiering · Execution',
      x: 400,
      y: 600,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Plan and execute successful product launches with clear GTM strategy.',
      whatYouLearn: [
        'Launch tiering methodology',
        'Go-to-market planning',
        'Cross-functional coordination',
        'Launch metrics and measurement',
      ],
      frameworks: [
        { name: 'Product Launch Framework', link: '/frameworks/product-launch' },
        { name: 'GTM Strategy Template', link: '/frameworks/gtm-strategy' },
        { name: 'Launch Checklist', link: '/frameworks/launch-checklist' },
      ],
      prerequisites: ['Messaging Framework'],
    },
    {
      id: 'enablement',
      title: 'Sales Enablement',
      subtitle: 'Materials · Training · Support',
      x: 100,
      y: 720,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Enable sales teams with materials, training, and ongoing support.',
      whatYouLearn: [
        'Sales collateral development',
        'Sales training programs',
        'Objection handling guides',
        'Competitive battle cards',
      ],
      frameworks: [
        { name: 'Sales Enablement Framework', link: '/frameworks/sales-enablement' },
        { name: 'Battle Card Template', link: '/frameworks/battle-cards' },
        { name: 'Sales Training Guide', link: '/frameworks/sales-training' },
      ],
      prerequisites: ['Buyer Personas'],
    },
    {
      id: 'content',
      title: 'Product Content',
      subtitle: 'Website · Collateral · Documentation',
      x: 400,
      y: 720,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Create comprehensive product content across all customer touchpoints.',
      whatYouLearn: [
        'Website copy optimization',
        'Product collateral suite',
        'Documentation strategy',
        'Case study development',
      ],
      frameworks: [
        { name: 'Product Content Framework', link: '/frameworks/product-content' },
        { name: 'Website Messaging Template', link: '/frameworks/website-messaging' },
        { name: 'Case Study Structure', link: '/frameworks/case-studies' },
      ],
      prerequisites: ['Product Launch'],
    },
    {
      id: 'pricing',
      title: 'Pricing & Packaging',
      subtitle: 'Strategy · Tiers · Communication',
      x: 250,
      y: 840,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Develop pricing strategy and packaging that maximizes value capture.',
      whatYouLearn: [
        'Pricing strategy frameworks',
        'Packaging tier design',
        'Price communication tactics',
        'Pricing research methods',
      ],
      frameworks: [
        { name: 'Pricing Strategy Framework', link: '/frameworks/pricing-strategy' },
        { name: 'Packaging Design Guide', link: '/frameworks/packaging-design' },
        { name: 'Price Testing Methods', link: '/frameworks/price-testing' },
      ],
      prerequisites: ['Sales Enablement', 'Product Content'],
    },
    {
      id: 'adoption',
      title: 'Product Adoption',
      subtitle: 'Onboarding · Activation · Retention',
      x: 250,
      y: 960,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Drive product adoption through optimized onboarding and activation.',
      whatYouLearn: [
        'Onboarding optimization',
        'Activation metric identification',
        'Feature adoption strategies',
        'User retention tactics',
      ],
      frameworks: [
        { name: 'Product Adoption Framework', link: '/frameworks/product-adoption' },
        { name: 'Onboarding Optimization', link: '/frameworks/onboarding-opt' },
        { name: 'Activation Playbook', link: '/frameworks/activation-playbook' },
      ],
      prerequisites: ['Pricing & Packaging'],
    },
    {
      id: 'feedback',
      title: 'Customer Feedback Loop',
      subtitle: 'Research · Insights · Iteration',
      x: 250,
      y: 1080,
      width: 300,
      height: 80,
      status: 'locked',
      description: 'Build systematic customer feedback loops to inform product evolution.',
      whatYouLearn: [
        'Feedback collection systems',
        'Customer insight synthesis',
        'Feature prioritization',
        'Product-market fit assessment',
      ],
      frameworks: [
        { name: 'Feedback Loop System', link: '/frameworks/feedback-loops' },
        { name: 'Customer Insight Framework', link: '/frameworks/customer-insights' },
        { name: 'PMF Assessment Guide', link: '/frameworks/pmf-assessment' },
      ],
      prerequisites: ['Product Adoption'],
    },
    {
      id: 'complete',
      title: '🎉 MASTERY',
      x: 300,
      y: 1200,
      width: 200,
      height: 60,
      status: 'locked',
      description: 'Congratulations on completing the Product Marketing roadmap!',
      whatYouLearn: [],
      frameworks: [],
      prerequisites: ['Customer Feedback Loop'],
    },
  ],

  connections: [
    { from: 'start', to: 'market-research', completed: true },
    { from: 'market-research', to: 'customer-research', completed: true },
    { from: 'customer-research', to: 'positioning', completed: false },
    { from: 'positioning', to: 'messaging', completed: false },
    { from: 'messaging', to: 'persona', completed: false },
    { from: 'messaging', to: 'launch', completed: false },
    { from: 'persona', to: 'enablement', completed: false },
    { from: 'launch', to: 'content', completed: false },
    { from: 'enablement', to: 'pricing', completed: false },
    { from: 'content', to: 'pricing', completed: false },
    { from: 'pricing', to: 'adoption', completed: false },
    { from: 'adoption', to: 'feedback', completed: false },
    { from: 'feedback', to: 'complete', completed: false },
  ],
}
